import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Elijah the Prophet",
            artist: "Old Testament",
            cover: "https://seedsoffaith.cph.org/wp-content/uploads/2018/02/cph_30240958230.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ia800802.us.archive.org/13/items/bible-stories-audio-book-ot/24_Elijah%20the%20Prophet.mp3",
            active: true,
        },
        {
            name:"Daniel and the Lions Den",
            artist: "Old Testament",
            cover: "https://www.learnreligions.com/thmb/z6uJPS6J45_ULspDIIJoavn53yg=/1500x1000/filters:fill(auto,1)/DanielLionDen-58fa4d7d3df78ca1590b989f.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ia800802.us.archive.org/13/items/bible-stories-audio-book-ot/26_Daniel%20and%20the%20Lions%20Den.mp3",
            active: false,
        },
        {
            name:"Adam and Eve",
            artist: "Old Testament",
            cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4o_hr2B1lAhhcnqtFPXothkLRw5TbCtDjIA&usqp=CAU",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://ia800207.us.archive.org/23/items/BibleStories/011AdamAndEve.mp3",
            active: false,
        },
        {
            name:"Cain and Abel",
            artist: "Old Testament",
            cover: "https://assetsnffrgf-a.akamaihd.net/assets/m/1101978058/univ/art/1101978058_univ_lsr_xl.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ia800207.us.archive.org/23/items/BibleStories/012CainAbel.mp3",
            active: false,
        },
        {
            name:"Noah and the Ark",
            artist: "Old Testament",
            cover: "https://i.pinimg.com/736x/59/3d/b0/593db0e5745a6e7833ddc39e598828af.jpg",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://ia800207.us.archive.org/23/items/BibleStories/021NoahAndTheArk.mp3",
            active: false,
        },
        {
            name:"Joshua",
            artist: "Old Testament",
            cover: "https://i.pinimg.com/736x/74/ac/67/74ac67c809617b43012339ef9558b2ab--bible-doctrine-joshua-.jpg",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://ia801605.us.archive.org/3/items/dbsot_1703_librivox/dbsot_09_kjv.mp3",
            active: false,
        },
        {
            name:"Miracles of Jesus",
            artist: "New Testament",
            cover: "https://assetsnffrgf-a.akamaihd.net/assets/m/1102009468/univ/art/1102009468_univ_lsr_xl.jpg",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "https://ia800608.us.archive.org/0/items/CatholicKidsBibleStories/Miracles%20of%20Jesus.mp3",
            active: false,
        },
        {
            name:"Road to Emmaus",
            artist: "New Testament",
            cover: "https://www.gregolsen.com/wp-content/uploads/2014/08/Road-to-Emmaus.jpg",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://media.sabbathschoolpersonalministries.org/sabbathschoolaudio/Primary/P-C-Q2-L08.mp3",
            active: false,
        },
        {
            name:"The Temple Tower",
            artist: "Old Testament",
            cover: "https://www.worldreligionnews.com/wp-content/uploads/2017/05/towerofbabel-5-10-2017.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://ia800207.us.archive.org/23/items/BibleStories/022TheTempleTower.mp3",
            active: false,
        },
        {
            name:"David and Saul",
            artist: "Old Testament",
            cover: "https://assetsnffrgf-a.akamaihd.net/assets/m/1102016051/univ/art/1102016051_univ_cnt_2_xl.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://ia800802.us.archive.org/13/items/bible-stories-audio-book-ot/20_David%20and%20Saul.mp3",
            active: false,
        },
        {
            name:"Abraham and Isaac ",
            artist: "Old Testament",
            cover: "https://centralldm.es/wp-content/uploads/2021/11/412-ot-abraham-atonement.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://ia800802.us.archive.org/13/items/bible-stories-audio-book-ot/03_Abraham%20and%20Isaac.mp3",
            active: false,
        },
        {
            name:"The Call of Abraham",
            artist: "Old Testament",
            cover: "https://ssnet.org/wp-content/uploads/2015/06/GoodSalt.com-mcbas0005-263x300.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://ia800207.us.archive.org/23/items/BibleStories/031TheCallOfAbraham.mp3",
            active: false,
        },
        {
            name:"The Three Strangers",
            artist: "Old Testament",
            cover: "https://www.dominicaslerma.es/images/Oracion/rinc%C3%B3nparaorar/2017/001-octubre/ni%C3%B1os2.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://ia800207.us.archive.org/23/items/BibleStories/032TheThreeStrangers.mp3",
            active: false,
        },
        {
            name:"Samuel",
            artist: "Old Testament",
            cover: "https://media.freebibleimages.org/stories/FB_Moody_Samuel/overview-images/022-moody-samuel.jpg?1643121159",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://ia600802.us.archive.org/13/items/bible-stories-audio-book-ot/18_Samuel.mp3",
            active: false,
        },
        {           
            name:"Sodom",
            artist: "Old Testament",
            cover: "https://1.bp.blogspot.com/-K2WXr6v5H1I/WpMOz31-z0I/AAAAAAAAEQI/ty3n5oZBS1Ij_UWN8WUY8gLAH1RbDScOgCLcBGAs/s1600/download%2B%252816%2529.jpeg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://ia800207.us.archive.org/23/items/BibleStories/041Sodom.mp3",
            active: false,
        },
        {
        
            name:"The Story of Esther",
            artist: "Old Testament",
            cover: "https://i.ytimg.com/vi/5-SGdrHxK5k/maxresdefault.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://ia800802.us.archive.org/13/items/bible-stories-audio-book-ot/27_The%20Story%20of%20Esther.mp3",
            active: false,
        },
        {

        name:"The Story of Ruth",
        artist: "Old Testament",
        cover: "https://psicologiacatolicaintegral.com/wp-content/uploads/2017/10/RUT.jpg",
        id: uuidv4(),
        color: ["#FDE1A9", "#A46874"],
        audio: "https://ia800802.us.archive.org/13/items/bible-stories-audio-book-ot/17_The%20Story%20of%20Ruth.mp3",
        active: false,
    
        },
    ];
}

export default chillHop;


